# Generated by Django 2.2.5 on 2019-11-17 20:57

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resorts',
            new_name='Resort',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='resort_id',
            new_name='resort',
        ),
        migrations.RenameField(
            model_name='resort',
            old_name='resort_id',
            new_name='resort',
        ),
    ]
